### PR TITLE
Updating chaos basic selections for new 9e codex

### PR DESCRIPTION
**Pull request by JLoach**
Updating a few 9e codex name differences in the basic selections, there are probably a lot more, these are just the ones I noticed so far, I will update others as I see them.

### CODE REVIEW

**Comment by maybe-hello-world** [comment]
I suggest adding Excruciator cannons from Venomcrawler too

**Comment by JLoach** [comment]
For some reason, excruciator cannons already do not get added to the output when I test it, so not needed?

**Comment by maybe-hello-world** [comment]
Oh, found it.
Currently, there're chaos.yml and csm.yml files. csm.yml is for units that are in CSM codex only and chaos for units that can be in different codices (1000sons, deathguard, daemons, etc.). As venomcrawler is a csm-only unit, it's in csm.yml.

May I ask you to move master of possession and venomcrawler info to csm.yml?
Thanks.

**Review by maybe-hello-world — CHANGES_REQUESTED** [review]
See the comment above.

**Comment by JLoach** [comment]
Moved those to the correct file, sorry about that.

**Comment by maybe-hello-world** [comment]
No worries, thank you so much for the help :)

**Review by maybe-hello-world — APPROVED** [review]

**Pull request merged**
